'use client';
import {useEffect,useState} from 'react';
import {Sprout,Sun,Moon,BookOpen,CalendarDays,Sparkles,ChevronLeft,ChevronRight,Check,Plus,Minus,CloudCheck,RefreshCw,Share,Trophy,Tablet} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {daily,weekly,phases,START,END,todayKey,addDays,monday,inTerm,clampDate,shortDate,dateCount,dailyCount,weekCount} from '@/lib/plan';
import {useProgress} from '@/lib/use-progress';
import {StudyCalendar} from '@/components/study-calendar';
export default function Home(){
 const {records,ready,busy,error,auth,today,refresh,save,failed}=useProgress();
 const [date,setDate]=useState(()=>clampDate(todayKey()));const [tab,setTab]=useState('daily');
 const [lastToday,setLastToday]=useState(today);
 useEffect(()=>{if(today!==lastToday){if(date===lastToday)setDate(clampDate(today));setLastToday(today);}},[today,date,lastToday]);
 const week=monday(date),days=Array.from({length:7},(_,i)=>addDays(week,i));
 const maxDate=clampDate(today),editable=ready&&!busy&&date===today&&inTerm(today),weekEditable=ready&&!busy&&week===monday(today)&&inTerm(today);
 const count=dailyCount(records,date),completedWeeks=weekCount(records,week);
 const weekChecks=days.reduce((n,d)=>n+dailyCount(records,d),0);
 const elapsedDays=dateCount(START,today>END?END:today);
 const allDaily=Object.entries(records).filter(([k])=>k.startsWith('d:')&&k.split(':')[1]<=today).reduce((n,[,v])=>n+v,0);
 const englishChecks=Object.entries(records).filter(([k])=>/^d:.*:(listen|word|read)$/.test(k)&&k.split(':')[1]<=today).reduce((n,[,v])=>n+v,0);
 const stories=Object.entries(records).filter(([k])=>/^w:.*:story$/.test(k)).reduce((n,[,v])=>n+v,0);
 let streak=0;for(let d=records[`d:${today}:word`]?today:addDays(today,-1);d>=START&&d<=END&&records[`d:${d}:word`];d=addDays(d,-1))streak++;
 const rate=elapsedDays?Math.round(allDaily/(elapsedDays*5)*100):0;
 const englishRate=elapsedDays?Math.round(englishChecks/(elapsedDays*3)*100):0;
 const mark=(key:string,value:number)=>{void save(key,value).catch(()=>{});};
 function goalCheck(id:string,label:string,displayLabel=label){return <label className="goal-check"><Checkbox checked={!!records[`g:${id}`]} disabled={!ready||busy} onCheckedChange={c=>mark(`g:${id}`,c?1:0)} aria-label={label}/><span>{displayLabel}</span></label>;}
 function move(n:number){setDate(clampDate(addDays(date,n)>maxDate?maxDate:addDays(date,n)));}
 return <main className="app"><header className="top"><div className="brand"><span className="brand-icon"><Sprout/></span><b>郑艺的成长手账</b><span className="semester">三年级 · 上学期</span></div><div className="status" aria-live="polite">{busy?<RefreshCw size={16}/>:<CloudCheck size={17}/>}<span>{busy?'正在保存…':error?'连接需要检查':ready?'记录已同步':'正在读取记录…'}</span></div></header>
 <div className="workspace"><section className="intro"><p className="eyebrow">每天一小步，成长看得见</p></section>
 {error&&<div role="alert" className="error"><span>{error}</span>{auth?<a href="/signin-with-chatgpt?return_to=%2F" target="_top">重新登录</a>:<div className="error-actions">{failed&&<button disabled={busy} onClick={()=>void save(failed.key,failed.value,failed.expected).catch(()=>{})}>重试保存</button>}<button disabled={busy} onClick={()=>void refresh()}>刷新记录</button></div>}</div>}
 <Tabs value={tab} onValueChange={setTab}>
 {tab!=='goals'&&<div className="date-toolbar"><div className="date-control"><button className="icon-button" aria-label={tab==='daily'?'前一天':'上一周'} disabled={date<=START} onClick={()=>move(tab==='daily'?-1:-7)}><ChevronLeft size={20}/></button><label className="date-label"><CalendarDays size={17}/><input type="date" aria-label="选择日期，查看历史记录" min={START} max={maxDate} value={date} onChange={e=>{if(e.target.value>=START&&e.target.value<=maxDate)setDate(e.target.value);}}/></label><button className="icon-button" aria-label={tab==='daily'?'后一天':'下一周'} disabled={tab==='daily'?date>=maxDate:week>=monday(maxDate)} onClick={()=>move(tab==='daily'?1:7)}><ChevronRight size={20}/></button><button className="text-button" onClick={()=>setDate(maxDate)}>{inTerm(today)?'回到今天':'学期末'}</button></div><span className="date-hint">{tab==='weekly'?`${shortDate(week)} — ${shortDate(addDays(week,6))}`:date===today?'今天的事，今天完成':'历史记录 · 只看进步，不补卡'}</span></div>}
 <TabsContent value="daily"><div className="columns"><section className="panel daily-panel"><div className="week-strip" aria-label="本周每日完成情况">{days.map((d,i)=><button key={d} onClick={()=>setDate(d)} disabled={!inTerm(d)||d>today} className={d===date?'selected':''} aria-label={`${shortDate(d)}，${dailyCount(records,d)}项完成`} aria-pressed={d===date}><span>{['一','二','三','四','五','六','日'][i]}</span><b>{Number(d.slice(8))}</b><span className={'day-mark '+(dailyCount(records,d)===5?'full':'')}>{dailyCount(records,d)===5?<Check size={12}/>:dailyCount(records,d)?`${dailyCount(records,d)}/5`:'·'}</span></button>)}</div><div className="section-head"><h2>{date===today?'今天的小任务':shortDate(date)+'的小任务'}</h2><span>{ready?`${count} / 5 已完成`:'读取中…'}</span></div>
 {['中午','睡觉前'].map((s,i)=><div key={s} className="task-group"><h3>{i?<Moon/>:<Sun/>}{s}<span>{i?'好好收尾，安心入睡':'轻松开始，积累一点点'}</span></h3>{daily.slice(i?2:0,i?5:2).map(t=><label key={t.id} className={'task '+(records[`d:${date}:${t.id}`]?'is-done':'')+(!editable?' locked':'')}><span className="emoji">{t.emoji}</span><span className="task-copy"><strong>{t.title}</strong><small>{t.desc}</small></span><Checkbox aria-label={t.title} checked={!!records[`d:${date}:${t.id}`]} disabled={!editable} onCheckedChange={c=>mark(`d:${date}:${t.id}`,c?1:0)}/></label>)}</div>)}
 {count===5&&ready&&<div className="celebrate" role="status"><Trophy size={21}/><span>{busy?'正在保存最后一个勾…':'这一天，五个小习惯全部完成！'}</span></div>}</section>
 <aside><section className="progress-card"><span className="small-title">{date===today?'今天的收获':'这一天的收获'}</span><div className="big-count">{ready?count:'—'}<small>/ 5</small></div><p>{count===5?'给认真坚持的自己一个拥抱！':'每一个勾，都是一次进步'}</p><Progress aria-label="每日任务进度" value={count*20}/><div className="progress-foot"><span>每日任务进度</span><b>{count*20}%</b></div><div className="mini-stats"><div><strong>{weekChecks}</strong><span>本周已打卡</span></div><div><strong>{streak}<small> 天</small></strong><span>WordEcho 连续</span></div></div></section><section className="gentle"><BookOpen/><h3>慢慢来，也很棒</h3><p>当天没做到的不补、不批评。周日和爸爸妈妈一起，看看这一周的小进步。</p></section><details className="install"><summary><Tablet size={17}/> 放到 iPad 主屏幕</summary><ol><li>用 iPad 的 Safari 打开应用链接。</li><li>登录当前的 ChatGPT 账号。</li><li>点“分享” → “添加到主屏幕”；如有“作为网页 App 打开”，将它开启。</li></ol><p>打卡需要联网，记录保存在云端。添加后直接点主屏幕图标打开。</p></details></aside></div></TabsContent>
 <TabsContent value="weekly"><div className="columns"><section className="panel"><div className="section-head"><h2>本周的 {weekly.length} 个小目标</h2><span>{completedWeeks} / {weekly.length} 已达标</span></div><p className="section-note">时间由你决定，完成一次就记一次。</p><div className="weekly-list">{weekly.map(t=>{const key=`w:${week}:${t.id}`,n=records[key]||0;return <div className={'weekly-task '+(n>=t.target?'achieved':'')} key={t.id}><div className="weekly-main"><span className="emoji">{t.emoji}</span><div className="task-copy"><strong>{t.title}</strong><small>{t.desc}</small></div></div><div className="weekly-bottom"><span className={'target-label '+(n>=t.target?'reached':'')}>{n>=t.target?<><Check size={15}/>本周达标</>:`每周 ${t.target>1?'至少 ':''}${t.target} ${t.unit}`}</span>{t.target===1?<label className="weekly-check"><span>{n?'已完成':'完成打卡'}</span><Checkbox checked={!!n} aria-label={t.title} disabled={!weekEditable} onCheckedChange={c=>mark(key,c?1:0)}/></label>:<div className="counter"><button className="icon-button" aria-label={`${t.title}减少一次`} disabled={!weekEditable||n===0} onClick={()=>mark(key,n-1)}><Minus size={18}/></button><span aria-live="polite"><b>{n}</b> / {t.target} {t.unit}</span><button className="icon-button plus" aria-label={`${t.title}增加一次`} disabled={!weekEditable||n>=t.target} onClick={()=>mark(key,n+1)}><Plus size={18}/></button></div>}</div></div>;})}</div>{completedWeeks===weekly.length&&ready&&<div className="celebrate" role="status"><Trophy size={21}/>{busy?'正在保存本周记录…':'本周全部达标，给自己一个大大的赞！'}</div>}</section><aside><section className="progress-card"><span className="small-title">本周的成就</span><div className="big-count">{ready?completedWeeks:'—'}<small>/ {weekly.length}</small></div><p>完成一个目标，就离梦想近一步</p><Progress value={completedWeeks/weekly.length*100} aria-label="每周目标进度"/><div className="progress-foot"><span>本周目标进度</span><b>{Math.round(completedWeeks/weekly.length*100)}%</b></div></section><section className="gentle"><CalendarDays/><h3>周日，一起聊一聊</h3><p>这周最开心的事是什么？哪件事想换个做法？连续两周不达标，再请爸爸妈妈一起调整。</p></section><div className="week-note">{week===monday(today)&&inTerm(today)?'本周可以随时记录，达到数量会自动打勾。':'正在查看历史周；记录保留，不补打卡。'}</div></aside></div></TabsContent>
 <TabsContent value="goals"><StudyCalendar records={records} today={today} ready={ready} onOpen={(selected,view)=>{setDate(clampDate(selected));setTab(view);window.scrollTo({top:0});}}/><div className="goals-grid"><section className="panel goal-card"><span className="goal-tag">🌱 生活习惯</span><h3>自己安排，少一点拖拉</h3><p>用打卡代替催促，日常事务自己确认。</p><div className="metric"><b>{ready?rate:'—'}<small>%</small></b><span>学期每日打卡率 · 目标 ≥ 90%</span></div><Progress value={rate} aria-label="学期每日完成率"/><p className="metric-note">从 9 月 1 日至今天，按每天 5 项计算。</p>{goalCheck('dental','12 月前完成牙科初诊 + 干预方案')}</section><section className="panel goal-card"><span className="goal-tag">🔤 英语</span><h3>每天听、读、记单词</h3><p>每天三项缺一不可，WordEcho 连续打卡。</p><div className="metric"><b>{ready?englishRate:'—'}<small>%</small></b><span>英语三项打卡率 · 目标 ≥ 90%</span></div><Progress value={englishRate} aria-label="英语打卡率"/><p className="metric-note">从 9 月 1 日至今天，按每天 3 项计算。</p><div className="goal-foot">WordEcho 已连续打卡 <b>{streak}</b> 天</div></section><section className="panel goal-card"><span className="goal-tag">🧮 数学</span><h3>学完六年级，冲刺 S 班</h3><p>认真完成桃李未来每周作业</p>{goalCheck('math-all','完成六年级数学学习')}{goalCheck('s-class','进入桃李未来S班')}</section><section className="panel goal-card"><span className="goal-tag">📖 语文</span><h3>看完凯叔100个故事</h3><p>每周看约 7 个凯叔故事并简单复述，约 15 周看完。</p><div className="metric"><b>{ready?stories:'—'}<small>/ 100</small></b><span>已看完并复述的故事</span></div><Progress value={Math.min(100,stories)} aria-label="100个故事进度"/><p className="metric-note">由每周故事记录自动累计。</p></section></div><section className="panel robot-panel"><div className="section-head"><div><span className="goal-tag">🤖 科创项目</span><h2>我的 MiniDuck 跟随机器人</h2></div><span>{phases.filter(p=>records[`g:${p.id}`]).length} / 4 阶段</span></div><p className="section-note">每周一次整块时间，建议周六上午。孩子主导动手，家长做助手。</p><div className="phases">{phases.map((p,i)=><div className={'phase '+(records[`g:${p.id}`]?'phase-done':'')} key={p.id}><div className="phase-heading"><span className="phase-num">{records[`g:${p.id}`]?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><h3>{p.title}</h3>{goalCheck(p.id,'完成'+p.title,'完成')}</div><span className="phase-time">{p.time}</span><p>{p.desc}</p></div>)}</div></section></TabsContent><TabsList className="nav" aria-label="打卡视图"><TabsTrigger value="daily"><Sun/>每日打卡</TabsTrigger><TabsTrigger value="weekly"><CalendarDays/>每周任务</TabsTrigger><TabsTrigger value="goals"><Sparkles/>学期目标</TabsTrigger></TabsList></Tabs><footer><Sprout size={16}/>不卡钟点，以打卡代替催促。<span>日期按北京时间</span></footer></div></main>;
}
